version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: words-mongo-db

    # local dir is '_db', dir in docker container is 'data/db'
    volumes:
      - ./_db:/data/db

    # 映射外部端口, 通过 9600 端口可以访问到容器内部的数据库
    ports:
      - 9600:27017
    expose:
      - 27017
    restart: unless-stopped