// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
export {}
